[versions]
kotlinVersion = "2.1.21"
jvm-language = "21"
jvm-compiler = "21"

assertj = "3.27.4"
arrow = "2.1.2"
binaryCompabilityValidator = "0.13.2"
cassandra = "4.19.1"
coroutines = "1.9.0"
jackson = "2.18.3"
junit-parametrized = "5.13.4"
konform = "0.11.0"
konvert = "4.2.0"
kafka-client = "3.7.0"
kotlinx-atomicfu = "0.23.2"
kotlin-reflect = "2.2.10"
kotlinx-coroutines = "1.10.2"
kotlinx-datetime = "0.6.2"
ktor = "3.3.0"
liquibase-core = "4.33.0"
liquibase-cassandra = "4.33.0"
logback = "1.5.3"
logback-appenders = "1.8.8"
logback-logstash = "7.4"
logger-fluentd = "0.3.4"
mockk = "1.14.6"
openapi-generator = "7.14.0"
testcontainers-core = "2.0.2"
testcontainers-cassandra = "2.0.2"
testcontainers-kafka = "1.21.3"
testcontainers-junit = "1.21.3"

[libraries]
assertj = { module = "org.assertj:assertj-core", version.ref = "assertj" }
arrow = { module = "io.arrow-kt:arrow-core", version.ref = "arrow" }

db-cassandra-core = { module = "org.apache.cassandra:java-driver-core", version.ref = "cassandra" }
db-cassandra-qbuilder = { module = "org.apache.cassandra:java-driver-query-builder", version.ref = "cassandra" }
db-cassandra-kapt = { module = "org.apache.cassandra:java-driver-mapper-processor", version.ref = "cassandra" }
db-cassandra-mapper = { module = "org.apache.cassandra:java-driver-mapper-runtime", version.ref = "cassandra" }

coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
coroutines-jdk9 = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-jdk9", version.ref = "coroutines" }
jackson-kotlin = { module = "com.fasterxml.jackson.module:jackson-module-kotlin", version.ref = "jackson" }
jackson-datatype = { module = "com.fasterxml.jackson.datatype:jackson-datatype-jsr310", version.ref = "jackson" }
junit-kotlin = { module = "org.jetbrains.kotlin:kotlin-test-junit5", version.ref = "kotlinVersion" }
junit-parametrized = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "junit-parametrized" }
kafka-client = { module = "org.apache.kafka:kafka-clients", version.ref = "kafka-client" }
konform = { module = "io.konform:konform-jvm", version.ref = "konform" }
konvert-lib = { module = "io.mcarle:konvert", version.ref = "konvert" }
konvert-api = { module = "io.mcarle:konvert-api", version.ref = "konvert" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin-reflect" }
kotlinx-atomicfu = { module = "org.jetbrains.kotlinx:atomicfu", version.ref = "kotlinx-atomicfu" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-slf4j = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-slf4j", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }

ktor-client-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }

ktor-server-core = { module = "io.ktor:ktor-server-core", version.ref = "ktor" }
ktor-server-double-receive = { module = "io.ktor:ktor-server-double-receive", version.ref = "ktor" }
ktor-server-netty = { module = "io.ktor:ktor-server-netty", version.ref = "ktor" }
ktor-server-content-negotiation = { module = "io.ktor:ktor-server-content-negotiation", version.ref = "ktor" }
ktor-server-default-headers = { module = "io.ktor:ktor-server-default-headers", version.ref = "ktor" }
ktor-server-host-common = { module = "io.ktor:ktor-server-host-common", version.ref = "ktor" }
ktor-server-status-pages = { module = "io.ktor:ktor-server-status-pages", version.ref = "ktor" }
ktor-serialization-jackson = { module = "io.ktor:ktor-serialization-jackson", version.ref = "ktor" }
ktor-server-test-host = { module = "io.ktor:ktor-server-test-host", version.ref = "ktor" }

liquibase-core = { module = "org.liquibase:liquibase-core", version.ref = "liquibase-core" }
liquibase-cassandra = { module = "org.liquibase.ext:liquibase-cassandra", version.ref = "liquibase-cassandra" }

logback = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
logback-appenders = { module = "com.sndyuk:logback-more-appenders", version.ref = "logback-appenders" }
logback-logstash = { module = "net.logstash.logback:logstash-logback-encoder", version.ref = "logback-logstash" }
logger-fluentd = { module = "org.fluentd:fluent-logger", version.ref = "logger-fluentd" }

mockk = { module = "io.mockk:mockk-jvm", version.ref = "mockk" }

testcontainers-core = { module = "org.testcontainers:testcontainers", version.ref = "testcontainers-core" }
testcontainers-junit = { module = "org.testcontainers:junit-jupiter", version.ref = "testcontainers-junit" }
testcontainers-kafka = { module = "org.testcontainers:kafka", version.ref = "testcontainers-kafka" }
testcontainers-cassandra = { module = "org.testcontainers:testcontainers-cassandra", version.ref = "testcontainers-cassandra" }

plugin-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlinVersion" }
plugin-binaryCompatibilityValidator = { module = "org.jetbrains.kotlinx:binary-compatibility-validator", version.ref = "binaryCompabilityValidator" }

[bundles]
cassandra = ["db-cassandra-core", "db-cassandra-mapper", "db-cassandra-qbuilder"]
jackson = [ "jackson-kotlin", "jackson-datatype" ]
junit = [ "junit-kotlin", "assertj", "junit-parametrized" ]
kotlinx-coroutines = [ "kotlinx-coroutines-core", "kotlinx-coroutines-slf4j" ]
testcontainers = [ "testcontainers-core", "testcontainers-junit" ]

[plugins]
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlinVersion" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlinVersion" }
ktor = { id = "io.ktor.plugin", version.ref = "ktor" }
openapi-generator = { id = "org.openapi.generator", version.ref = "openapi-generator" }